const FETCH_CURRENT_RATE_BEGIN = "FETCH_CURRENT_RATE_BEGIN";
const FETCH_CURRENT_RATE_SUCCESS = "FETCH_CURRENT_RATE_SUCCESS";
const FETCH_CURRENT_RATE_FAILURE = "FETCH_CURRENT_RATE_FAILURE";

export {
    FETCH_CURRENT_RATE_BEGIN,
    FETCH_CURRENT_RATE_SUCCESS,
    FETCH_CURRENT_RATE_FAILURE,
};
